### ISSUE TITLE
Loosing internal state when doing hot reload

### ISSUE THREAD

**Issue by truongsinh** [Glavin001/react-hot-ts#1]
```ts
// src/App.tsx
import * as React from "react";

export default class App extends React.Component<any, any> {
	private timer;
	private state = {
		counter: 0
	}
	constructor(prop) {
		super(prop)
		this.timer = setInterval(()=>{
			
		this.setState({counter: this.state.counter + 10})
		},1000)
		console.log("timer", this.timer )
		
	}
    render() {
        return (
            <div>
                <h1>Hello world!</h1>
                <div>Welcome to hot-reloading React written in TypeScript! {this.state.counter}</div>
            </div>
        );
    }
}
```

When I change the behavior of `this.state.counter + 10` to `this.state.counter - 10` for example, after module reload, the internal state get reset to `0`. Is there something we can further configure, or is it because of (already closed bug) https://github.com/gaearon/react-hot-loader/issues/276?

**Comment by Glavin001** [comment]
I have experienced the same issue however have not found a solution yet. Suggestions / Pull Requests welcome. Thanks!
