### ISSUE TITLE
Update index.tsx for Webpack 2

### ISSUE THREAD

**Issue by tansongyang** [Glavin001/react-hot-ts#13]
I notice that this project uses Webpack 2. According to the [docs](https://github.com/gaearon/react-hot-loader/tree/master/docs#webpack-2), , `index.tsx` can be simplified like this:

```TypeScript
if (module.hot) {
  module.hot.accept("./App", () => {
    ReactDOM.render(
      <AppContainer>
        <App />
      </AppContainer>
      ,
      rootEl
    );
  });
}
```

Would you like a pull request?

**Comment by Glavin001** [comment]
Pull Requests welcome. Thanks in advance!

**Comment by tansongyang** [comment]
Closing because, after further investigation, it turns out this is presently only possible with Babel, _not_ with TypeScript.
