### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by Derek-X-Wang** [Glavin001/react-hot-ts#4]
Hi,

I have done:
`git clone https://github.com/Glavin001/react-hot-ts.git`
`cd react-hot-ts && npm i`
`npm start`

It doesn't compile, here is the error message:
<img width="641" alt="screen shot 2017-03-08 at 3 38 33 pm" src="https://cloud.githubusercontent.com/assets/6364170/23729313/080b6a0c-0416-11e7-9d6b-dd661495b6c5.png">

log:
[log.txt](https://github.com/Glavin001/react-hot-ts/files/829289/log.txt)

**Comment by Sedaj** [comment]
same problem

**Comment by originalmoose** [comment]
I found switching out awesome-typescript-loader for ts-loader fixed the error message above. Then I was getting an error about `./src/components/Hello.tsx` missing so I ended up with the following tsconfig file.

    {
      "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react",
        "baseUrl": "./src"
      },
      "exclude": [
        "node_modules"
      ]
    }

After making those changes everything seemed to work.

**Comment by Derek-X-Wang** [comment]
It works!!
Thanks a lot!
